# Generated by Django 6.0.1 on 2026-01-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Müştəri adı')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('voen', models.CharField(blank=True, max_length=50, verbose_name='VÖEN')),
                ('note', models.TextField(blank=True, verbose_name='Qeyd')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Məhsul adı')),
                ('bag_kg', models.PositiveIntegerField(verbose_name='1 kisə (kg)')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
        ),
    ]
