# Generated by Django 6.0.1 on 2026-01-19 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deyirman_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarix')),
                ('shift', models.CharField(choices=[('DAY', 'Gündüz'), ('NIGHT', 'Gecə')], max_length=10, verbose_name='Növbə')),
                ('status', models.CharField(choices=[('DRAFT', 'Qaralama'), ('CONFIRMED', 'Təsdiqlənmiş')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('total_kg_control', models.PositiveIntegerField(default=0, verbose_name='Ümumi istehsal (kg) - kontrol')),
                ('note', models.TextField(blank=True, verbose_name='Qeyd')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_bag', models.PositiveIntegerField(verbose_name='Kisə sayı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deyirman_app.product')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deyirman_app.production')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_no', models.CharField(max_length=20, unique=True, verbose_name='Satış No')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarix')),
                ('status', models.CharField(choices=[('DRAFT', 'Qaralama'), ('CONFIRMED', 'Təsdiqlənmiş'), ('CANCELLED', 'Ləğv')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('payment_type', models.CharField(choices=[('CASH', 'Nəğd'), ('CREDIT', 'Nisyə'), ('PARTIAL', 'Qismən')], default='CREDIT', max_length=10, verbose_name='Ödəniş növü')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cəm')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ödənən')),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Borc')),
                ('note', models.TextField(blank=True, verbose_name='Qeyd')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deyirman_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarix')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Məbləğ (AZN)')),
                ('note', models.TextField(blank=True, verbose_name='Qeyd')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='deyirman_app.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_bag', models.PositiveIntegerField(verbose_name='Kisə sayı')),
                ('unit_price_bag', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Qiymət (AZN/kisə)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deyirman_app.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deyirman_app.sale')),
            ],
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarix')),
                ('move_type', models.CharField(choices=[('IN', 'Giriş'), ('OUT', 'Çıxış')], max_length=5, verbose_name='Tip')),
                ('source', models.CharField(choices=[('PRODUCTION', 'İstehsal'), ('SALE', 'Satış')], max_length=20, verbose_name='Mənbə')),
                ('qty_bag', models.PositiveIntegerField(verbose_name='Kisə sayı')),
                ('ref_text', models.CharField(blank=True, max_length=50, verbose_name='İstinad')),
                ('shift', models.CharField(blank=True, max_length=10, verbose_name='Növbə (istehsal üçün)')),
                ('note', models.TextField(blank=True, verbose_name='Qeyd')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deyirman_app.product')),
            ],
        ),
    ]
