# Generated by Django 6.0.1 on 2026-01-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deyirman_app', '0002_production_productionitem_sale_payment_saleitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_no',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Satış No'),
        ),
    ]
